const document_types = [
  {
    document_type: 'utility_bill',
    label: 'Utility bill',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 350,
    icon: 'receipt-long',
    set: 'MaterialIcons',
  },
  {
    document_type: 'bank_statement',
    label: 'Bank statement',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 350,
    icon: 'account-balance',
    set: 'MaterialIcons',
  },
  {
    document_type: 'lease_or_rental_agreement',
    label: 'Lease or rental agreement',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 350,
    icon: 'apartment',
    set: 'MaterialIcons',
  },
  {
    document_type: 'mortgage_statement',
    label: 'Mortgage statement',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 300,
    icon: 'house',
    set: 'MaterialIcons',
  },
  {
    document_type: 'municipal_rate_and_taxes',
    label: 'Rates and taxes',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 300,
    icon: 'house',
    set: 'MaterialIcons',
  },
  {
    document_type: 'telephone',
    label: 'Telephone',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 300,
    icon: 'call',
    set: 'MaterialIcons',
  },
  {
    document_type: 'insurance_policy',
    label: 'Insurance policy',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 300,
    icon: 'request_quote',
    set: 'MaterialIcons',
  },
  {
    document_type: 'retail_store',
    label: 'Retail store',
    description: 'Make sure your address is clear',
    capture_description: 'Make sure your address is clear',
    capture_height: 300,
    icon: 'store',
    set: 'MaterialIcons',
  },
];
export default document_types;
