const colors = {
  primary: '#7E2045',
  secondary: '#2353AF',
  tertiary: '#c4c4c4',
  focus: '#7E2045',
  primaryContrast: '#f6f6f6',
  secondaryContrast: '#f6f6f6',
  tertiaryContrast: '#000000',
  focusContrast: '#000000',
  success: '#4A5',
  warning: '#F85',
  error: '#E43',
  positive: '#4A5',
  negative: '#E43',
  grey1: '#EEE',
  grey2: '#DDD',
  grey3: '#BBC',
  font: '#777',
  header: 'white',
  headerContrast: '#7E2045',
  authScreen: 'white',
  authScreenContrast: '#7E2045',
  surface: 'white',
  surfaceInput: 'white',
  surfaceCard: 'white',
  surfaceRear: '#DDD',
  tabNavigator: '#EEE',
  tabNavigatorInactive: '#777',
  tabNavigatorActive: '#7E2045',
};

const design = {
  general: {
    shadow: 3,
    cornerRadius: 5,
    elevation: 2,
    layout: 'default',
  },
  app: {
    surface: true,
    tabBarLabels: false,
  },
  cards: {
    shadow: 8,
    cornerRadius: 20,
    elevation: 3,
    layout: 'default',
    actionButtonsType: 'contained',
    showActions: true,
    title: {
      layout: '',
      titleScale: 'h6',
      subtitleScale: 'subtitle2',
    },
  },
  popUp: {
    shadow: 5,
    cornerRadius: 20,
    elevation: 2,
    layout: 'default',
  },
  buttons: {
    shadow: 10,
    cornerRadius: 3,
    elevation: 4,
    layout: 'default',
    rounded: true,
    colour: 'primary',
    bold: false,
  },
  wallets: {
    shadow: 8,
    cornerRadius: 5,
    elevation: 3,
    layout: 'mini',
    actionButtonsType: '',
    showActions: false,
    title: {
      layout: '',
      titleScale: 'h6',
      subtitleScale: 'subtitle2',
    },
    header: 'convBalance',
    headerActionType: 'text',
    balance: 'badge',
    headerColor: 'font',
  },
  rewards: {
    shadow: 8,
    cornerRadius: 5,
    elevation: 3,
    layout: 'rightAction',
    actionButtonsType: 'text',
    showActions: true,
    title: {
      layout: '',
      titleScale: 'h6',
      subtitleScale: 'subtitle2',
    },
  },
  products: {
    shadow: 8,
    cornerRadius: 5,
    elevation: 3,
    layout: 'default',
    actionButtonsType: 'text',
    showActions: true,
    title: {
      layout: '',
      titleScale: 'h6',
      subtitleScale: 'subtitle2',
    },
  },
  orders: {
    shadow: 8,
    cornerRadius: 5,
    elevation: 3,
    layout: 'rightAction',
    actionButtonsType: 'text',
    showActions: true,
    title: {
      layout: '',
      titleScale: 'h6',
      subtitleScale: 'subtitle2',
    },
  },
  campaigns: {
    shadow: 8,
    cornerRadius: 5,
    elevation: 3,
    layout: 'material',
    actionButtonsType: 'contained',
    showActions: true,
    title: {
      layout: '',
      titleScale: 'h6',
      subtitleScale: 'subtitle2',
    },
  },
  settings: {
    shadow: 8,
    cornerRadius: 5,
    elevation: 3,
    layout: 'default',
    actionButtonsType: 'text',
    showActions: true,
    title: {
      layout: '',
      titleScale: 'h6',
      subtitleScale: 'subtitle2',
    },
  },
  contacts: {},
  notifications: {
    shadow: 8,
    cornerRadius: 5,
    elevation: 3,
    layout: 'material',
    actionButtonsType: 'contained',
    showActions: true,
    title: {
      titleScale: 'h4',
      subtitleScale: 'subtitle1',
    },
  },
  home: {
    header: 'wallets',
    content: ['notifications', 'rewards', 'wallets'],
  },
  other: {
    floatingActionButtons: false,
    homeCardLayout: 'material',
    actionButtonsType: 'text',
  },
};

export { colors, design };
